services:
  app:
    image: romsper/qa-backend-playground:latest
    ports:
      - "1111:1111"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: playground
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: